### ISSUE TITLE
It freezes :( and, why it is obfuscated?

### ISSUE THREAD

**Issue by alexvornoffice** [PowerOfFusion/Surviv.io-cheat#1]
It freezes for me...

**Comment by PowerOfFusion** [comment]
Because I had to pay for this code. There are many files, so they are packed.
If I find some time, I will fix the rest.

**Comment by alexvornoffice** [comment]
You got the code from powerofuniverse? I thought he fixed the freezing issue... So go take your money back because the hack does not work... It freezessssss

**Comment by PowerOfFusion** [comment]
I did not buy it from him. I found the offer on mpc forum.
